# Production Configuration for Cardiac Dreamer Training
# This file contains all configurable parameters for training

model:
  # Model architecture parameters
  token_type: "patch"             # Token strategy (channel/patch) - NEW: patch uses spatial tokens
  d_model: 768                    # Transformer model dimension
  num_heads: 12                   # Number of attention heads
  num_layers: 6                   # Number of transformer layers
  feature_dim: 49                 # Spatial feature dimension (7x7=49) - used for channel mode
  in_channels: 1                  # Input image channels (grayscale)
  use_pretrained: true            # Use ImageNet pretrained ResNet34
  
  # Optimization parameters - WITH DATA NORMALIZATION
  lr: 1e-4                        # Moderate learning rate with normalized data
  weight_decay: 1e-5              # Balanced weight decay
  
  # Loss function parameters - NORMALIZED DATA VERSION
  lambda_t2_action: 1.0           # Set to 1.0 - paper uses equal weighting for at1 and at2
  smooth_l1_beta: 1.0             # Standard beta with normalized data
  primary_task_only: false        # Keep false to use both at1 and at2 losses
  
  
  # Advanced settings
  use_flash_attn: false           # Use flash attention (experimental)

training:
  # Data loading parameters
  batch_size: 4                   # Reasonable batch size
  num_workers: 2                  # Adjust based on CPU cores
  
  # Training schedule
  max_epochs: 150                 # Sufficient epochs for convergence
  early_stop_patience: 20         # Reasonable patience
  check_val_every_n_epoch: 1      # Validation frequency
  
  # Optimization settings - NORMALIZED DATA
  gradient_clip_val: 1.0          # Standard gradient clipping
  accumulate_grad_batches: 1      # Maintain effective batch size
  log_every_n_steps: 20           # Logging frequency
  
  # Hardware settings
  accelerator: "auto"             # Hardware accelerator (auto/gpu/cpu)
  precision: 32                   # Training precision 32
  
# Data configuration
data:
  # Automatic patient splitting ratios
  train_ratio: 0.7                # 70% for training
  val_ratio: 0.15                 # 15% for validation
  test_ratio: 0.15                # 15% for testing
  
  # Data augmentation
  augmentation:
    enabled: true                 # Enable with normalized data
    rotation_range: 5             # Small rotation augmentation
    brightness_range: 0.05        # Small brightness augmentation
    contrast_range: 0.05          # Small contrast augmentation

# Experiment tracking
experiment:
  # Weights & Biases (optional)
  use_wandb: true                     # start WandB
  wandb_project: "cardiac-dreamer"    # project name
  wandb_entity: null  # Set to your WandB username if needed
  
  # Tags for experiment organization
  tags:
    - "data_normalized"           # Data normalization implemented
    - "patch_tokens"              # NEW: Using patch token approach
    - "paper_formulation"
    - "cross_patient"
    - "stable_training"
    
  # Notes
  description: "Cardiac Dreamer with patch tokens - each spatial location as 512-dim token" 